refresh_btc_txs:
  cron: "*/10 * * * * *"
  class: "CheckTxsJob"
  args:
    - btc

refresh_eth_txs:
  cron: "*/10 * * * * *"
  class: "CheckTxsJob"
  args:
    - eth

sync_unconfirmed_btc_txs:
  cron: "*/5 * * * * *"
  class: "SyncUnconfirmedTxsJob"
  args:
    - "btc"

sync_unconfirmed_eth_txs:
  cron: "*/5 * * * * *"
  class: "SyncUnconfirmedTxsJob"
  args:
    - "eth"

sync_btc_missing_blocks:
  cron: "0 0 * * *"
  class: "SyncMissingBlocksJob"
  args:
    - "btc"

sync_eth_missing_blocks:
  cron: "0 0 * * *"
  class: "SyncMissingBlocksJob"
  args:
    - "eth"
