steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ["pull", "us.gcr.io/$PROJECT_ID/crypto-cold-store:prod-latest"]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - "build"
      - "--cache-from=us.gcr.io/$PROJECT_ID/crypto-cold-store:prod-latest"
      - "--file=ops/prod/Dockerfile"
      - "--tag=us.gcr.io/$PROJECT_ID/crypto-cold-store:prod-latest"
      - "--tag=us.gcr.io/$PROJECT_ID/crypto-cold-store:$REVISION_ID"
      - "."
images:
  - 'us.gcr.io/$PROJECT_ID/crypto-cold-store'
