apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: ccs-staging
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: ccs-testnet.bx8.io
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: http-port
